#!/usr/bin/env python3
"""Fetch Bilibili video subtitles/transcripts.

Supports:
  - CC subtitles (uploaded by UP主)
  - AI subtitles (auto-generated by Bilibili)
  - Whisper local transcription (fallback via API audio download)

Usage:
  python3 fetch_transcript.py "BV_URL"
  python3 fetch_transcript.py "BV_URL" --text-only
  python3 fetch_transcript.py "BV_URL" --timestamps
  python3 fetch_transcript.py "BV_URL" --whisper
"""

import argparse
import json
import os
import re
import sys
import tempfile
import urllib.request
import urllib.error
from typing import Optional


HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Referer": "https://www.bilibili.com",
}


def api_get(url: str, cookie: str = "") -> dict:
    """GET request to Bilibili API."""
    headers = dict(HEADERS)
    if cookie:
        headers["Cookie"] = cookie
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        print(f"HTTP Error {e.code}: {e.reason}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Request error: {e}", file=sys.stderr)
        sys.exit(1)


def extract_bvid(url: str) -> str:
    """Extract BV ID from various Bilibili URL formats."""
    if "b23.tv" in url:
        req = urllib.request.Request(url, headers=HEADERS)
        req.method = "HEAD"
        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                url = resp.url
        except Exception:
            pass

    m = re.search(r"(BV[\w]{10})", url)
    if m:
        return m.group(1)

    m = re.search(r"av(\d+)", url)
    if m:
        aid = m.group(1)
        data = api_get(f"https://api.bilibili.com/x/web-interface/view?aid={aid}")
        if data.get("code") == 0:
            return data["data"]["bvid"]
        print(f"Error: cannot resolve av{aid}", file=sys.stderr)
        sys.exit(1)

    print(f"Error: cannot extract BV ID from URL: {url}", file=sys.stderr)
    sys.exit(1)


def get_cid(bvid: str, page: int = 0) -> tuple:
    """Get CID and video info for a BV ID."""
    data = api_get(f"https://api.bilibili.com/x/player/pagelist?bvid={bvid}")
    if data.get("code") != 0 or not data.get("data"):
        print(f"Error: cannot get pagelist for {bvid}", file=sys.stderr)
        sys.exit(1)

    pages = data["data"]
    if page >= len(pages):
        page = 0

    cid = pages[page]["cid"]
    part_title = pages[page].get("part", "")
    return cid, part_title, len(pages)


def get_video_info(bvid: str) -> dict:
    """Get video metadata."""
    data = api_get(f"https://api.bilibili.com/x/web-interface/view?bvid={bvid}")
    if data.get("code") != 0:
        return {}
    return data.get("data", {})


def get_subtitle_url(bvid: str, cid: str, cookie: str = "") -> list:
    """Get subtitle URLs from player API."""
    url = f"https://api.bilibili.com/x/player/v2?bvid={bvid}&cid={cid}"
    data = api_get(url, cookie)
    if data.get("code") != 0:
        return []
    return data.get("data", {}).get("subtitle", {}).get("subtitles", [])


def download_subtitle_json(subtitle_url: str) -> dict:
    """Download subtitle JSON file."""
    if subtitle_url.startswith("//"):
        subtitle_url = "https:" + subtitle_url
    req = urllib.request.Request(subtitle_url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.loads(resp.read().decode("utf-8"))


def get_audio_url(bvid: str, cid: str) -> Optional[str]:
    """Get audio stream URL from Bilibili playurl API."""
    url = f"https://api.bilibili.com/x/player/playurl?bvid={bvid}&cid={cid}&fnval=16&qn=64"
    data = api_get(url)
    if data.get("code") != 0:
        return None
    dash = data.get("data", {}).get("dash", {})
    audio_list = dash.get("audio", [])
    if audio_list:
        return audio_list[0].get("baseUrl")
    return None


def download_audio(audio_url: str, output_path: str, referer: str = "") -> bool:
    """Download audio from URL with chunked reads."""
    headers = dict(HEADERS)
    if referer:
        headers["Referer"] = referer
    req = urllib.request.Request(audio_url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            total = 0
            with open(output_path, "wb") as f:
                while True:
                    chunk = resp.read(65536)
                    if not chunk:
                        break
                    f.write(chunk)
                    total += len(chunk)
            print(f"Downloaded {total} bytes", file=sys.stderr)
            return True
    except Exception as e:
        print(f"Download error: {e}", file=sys.stderr)
        return False


def whisper_transcribe(audio_path: str, language: str = "zh", model_size: str = "small") -> Optional[list]:
    """Transcribe audio using faster-whisper."""
    try:
        from faster_whisper import WhisperModel
    except ImportError:
        print("Error: faster-whisper not installed.", file=sys.stderr)
        print("Install: uv pip install faster-whisper", file=sys.stderr)
        return None

    try:
        print(f"Loading Whisper model ({model_size}, CPU)...", file=sys.stderr)
        model = WhisperModel(model_size, device="cpu", compute_type="int8")
        print("Transcribing...", file=sys.stderr)
        segments, info = model.transcribe(audio_path, language=language, beam_size=5)
        print(f"Detected language: {info.language} (prob: {info.language_probability:.2f})", file=sys.stderr)

        result = []
        for seg in segments:
            result.append({
                "from": seg.start,
                "to": seg.end,
                "content": seg.text.strip()
            })
        return result
    except Exception as e:
        print(f"Whisper error: {e}", file=sys.stderr)
        return None


def format_timestamp(seconds: float) -> str:
    """Convert seconds to HH:MM:SS format."""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    if h > 0:
        return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"


def main():
    parser = argparse.ArgumentParser(description="Fetch Bilibili video transcripts")
    parser.add_argument("url", help="Bilibili video URL or BV ID")
    parser.add_argument("--text-only", action="store_true", help="Output plain text only")
    parser.add_argument("--timestamps", action="store_true", help="Include timestamps")
    parser.add_argument("--page", type=int, default=0, help="Page/P number (0-indexed)")
    parser.add_argument("--whisper", action="store_true", help="Force Whisper fallback")
    parser.add_argument("--cookie", default="", help="Bilibili cookie for login-required videos")
    parser.add_argument("--json", action="store_true", help="Output raw JSON")
    parser.add_argument("--language", default="zh", help="Whisper language hint (default: zh)")
    parser.add_argument("--model", default="small", help="Whisper model size: tiny/base/small/medium/large-v3 (default: small)")
    args = parser.parse_args()

    # Extract BV ID
    bvid = extract_bvid(args.url)
    print(f"Video: {bvid}", file=sys.stderr)

    # Get video info
    video_info = get_video_info(bvid)
    title = video_info.get("title", bvid)
    duration = video_info.get("duration", 0)
    print(f"Title: {title}", file=sys.stderr)
    if duration:
        print(f"Duration: {format_timestamp(duration)}", file=sys.stderr)

    # Get CID
    cid, part_title, total_pages = get_cid(bvid, args.page)
    if total_pages > 1:
        print(f"Page: {args.page + 1}/{total_pages} - {part_title}", file=sys.stderr)

    subtitles = []
    source = "none"

    # Tier 1 & 2: Try CC/AI subtitles from API
    if not args.whisper:
        sub_list = get_subtitle_url(bvid, cid, args.cookie)
        if sub_list:
            cc_subs = [s for s in sub_list if not s.get("lan", "").startswith("ai")]
            ai_subs = [s for s in sub_list if s.get("lan", "").startswith("ai")]
            ordered = cc_subs + ai_subs

            for sub in ordered:
                lang = sub.get("lan_doc", sub.get("lan", "unknown"))
                print(f"Found subtitle: {lang}", file=sys.stderr)
                try:
                    sub_data = download_subtitle_json(sub["subtitle_url"])
                    body = sub_data.get("body", [])
                    if body:
                        subtitles = body
                        source = "cc" if not sub.get("lan", "").startswith("ai") else "ai"
                        print(f"Using: {source} subtitles ({len(subtitles)} entries)", file=sys.stderr)
                        break
                except Exception as e:
                    print(f"Failed to download subtitle: {e}", file=sys.stderr)
                    continue
        else:
            print("No CC/AI subtitles found, falling back to Whisper...", file=sys.stderr)

    # Tier 3: Whisper fallback (using Bilibili API audio stream)
    if not subtitles:
        if not args.whisper and source == "none":
            print("Auto-enabling Whisper transcription...", file=sys.stderr)

        referer = f"https://www.bilibili.com/video/{bvid}/"
        audio_url = get_audio_url(bvid, cid)

        if not audio_url:
            print("Error: cannot get audio stream URL", file=sys.stderr)
            sys.exit(1)

        with tempfile.NamedTemporaryFile(suffix=".m4s", delete=False) as tmp:
            audio_path = tmp.name

        try:
            print("Downloading audio stream...", file=sys.stderr)
            if download_audio(audio_url, audio_path, referer):
                subtitles = whisper_transcribe(audio_path, args.language, args.model)
                if subtitles:
                    source = "whisper"
                    print(f"Whisper: {len(subtitles)} segments", file=sys.stderr)
        finally:
            try:
                os.unlink(audio_path)
            except OSError:
                pass

    if not subtitles:
        print("Error: No subtitles available for this video.", file=sys.stderr)
        sys.exit(1)

    # Output
    if args.json:
        output = {
            "bvid": bvid,
            "title": title,
            "duration": duration,
            "source": source,
            "total_pages": total_pages,
            "current_page": args.page,
            "entries": len(subtitles),
            "subtitles": subtitles,
        }
        print(json.dumps(output, ensure_ascii=False, indent=2))
    elif args.text_only:
        print(f"# {title}\n")
        for item in subtitles:
            print(item.get("content", ""))
    elif args.timestamps:
        print(f"# {title}\n")
        for item in subtitles:
            ts = format_timestamp(item.get("from", 0))
            print(f"[{ts}] {item.get('content', '')}")
    else:
        print(f"# {title}")
        print(f"# Source: {source}\n")
        for item in subtitles:
            print(item.get("content", ""))


if __name__ == "__main__":
    main()
